apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: my-golang-app-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: therion84/myapp:v1
          ports:
            - containerPort: 33500
          livenessProbe:
            tcpSocket:
              port: 33500
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 33500
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"