name: Deploy to Existing Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # важно! нужен локальный runner с доступом к Minikube

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Load image to Minikube
      run: minikube image load myapp:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Print service URL
      run: minikube service myapp --url -n my-golang-app-space